create table tb_cidades (id int4 generated by default as identity, name varchar(255), estado_id int4, primary key (id));
create table tb_estados (id int4 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_cidades add constraint FKqoy3fxe4vvhaaf5qsw3dtbag7 foreign key (estado_id) references tb_estados;
INSERT INTO tb_estados(name) VALUES ('São Paulo');
INSERT INTO tb_cidades(estado_id,name) VALUES (1,'São Caetano Do Sul');
