INSERT INTO tb_estados(name) VALUES ('Acre');
INSERT INTO tb_estados(name) VALUES ('Alagoas');
INSERT INTO tb_estados(name) VALUES ('Amapá');
INSERT INTO tb_estados(name) VALUES ('Amazonas');
INSERT INTO tb_estados(name) VALUES ('Bahia');
INSERT INTO tb_estados(name) VALUES ('Ceará');
INSERT INTO tb_estados(name) VALUES ('Distrito Federa');
INSERT INTO tb_estados(name) VALUES ('Espírito Santo');
INSERT INTO tb_estados(name) VALUES ('Goiás');
INSERT INTO tb_estados(name) VALUES ('Maranhão');
INSERT INTO tb_estados(name) VALUES ('Mato Grosso');
INSERT INTO tb_estados(name) VALUES ('Mato Grosso do Sul');
INSERT INTO tb_estados(name) VALUES ('Minas Gerais');
INSERT INTO tb_estados(name) VALUES ('Pará');
INSERT INTO tb_estados(name) VALUES ('Paraíba');
INSERT INTO tb_estados(name) VALUES ('Paraná');
INSERT INTO tb_estados(name) VALUES ('Pernambuco');
INSERT INTO tb_estados(name) VALUES ('Piauí');
INSERT INTO tb_estados(name) VALUES ('Rio de Janeiro');
INSERT INTO tb_estados(name) VALUES ('Rio Grande do Norte');
INSERT INTO tb_estados(name) VALUES ('Rio Grande do Sul');
INSERT INTO tb_estados(name) VALUES ('Rondônia');
INSERT INTO tb_estados(name) VALUES ('Roraima');
INSERT INTO tb_estados(name) VALUES ('Santa Catarina');
INSERT INTO tb_estados(name) VALUES ('São Paulo');
INSERT INTO tb_estados(name) VALUES ('Sergipe');
INSERT INTO tb_estados(name) VALUES ('Tocantins');
